import Head from 'next/head'
import { useState } from "react";
import { Layout, Button, Modal, Form, Input } from "antd";
import { PlusOutlined } from "@ant-design/icons";
import MyHeader from '@/components/header';
import TableWithDetails from '@/components/table';

const { Content } = Layout;

export default function Home() {
  const [open, setopen] = useState(false);

  const [form] = Form.useForm();

  const onFinish = (values: any) => {
    console.log(values);
    setopen(false);
    form.resetFields();
  };

  const onCancel = () => {
    setopen(false);
    form.resetFields();
  };

  return (
    <>
      <Head>
      <title>Hotel CheckIn</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <MyHeader />
      <Content style={{ backgroundColor: "#fff" }}>
        <div className="site-layout-content">
          <section className="check-ins">
            <div>
              <h1 className="check-ins__title">CheckIns</h1>
              <p className="check-ins__description">Lorem ipsum dolor sit amet consectetur, adipisicing elit.</p>
            </div>
            <Button
              type="primary"
              icon={<PlusOutlined />}
              onClick={() => setopen(true)}
              className="add-button"
            >
              Add Check In
            </Button>
          </section>

          <TableWithDetails />

          <Modal
            title="New CheckIn"
            open={open}
            onCancel={onCancel}
            footer={null}
          >
            <Form form={form} onFinish={onFinish}>
              <Form.Item name="title">
                <Input placeholder="Check In Title" />
              </Form.Item>
              <Form.Item name="imageUrl">
                <Input placeholder="Image Url" />
              </Form.Item>
              <div style={{ textAlign: "right" }}>
                <Button style={{ marginRight: 8 }} onClick={onCancel}>
                  Cancel
                </Button>
                <Button type="primary" className="add-button" htmlType="submit">
                  Create Check In
                </Button>
              </div>
            </Form>
          </Modal>
        </div>
      </Content>
    </Layout>
    </>
  );
}
