import Head from "next/head";
import { useCallback, useEffect, useState } from "react";
import { Layout, Button, Modal, message } from "antd";
import { PlusOutlined } from "@ant-design/icons";
import MyHeader from "@/components/layout/header";
import TableWithDetails from "@/components/table";
import MyForm from "@/components/form";
import styles from "../styles/Home.module.scss";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "../firebase/firebase";
import router from "next/router";

const { Content } = Layout;

export default function Home() {
  const [open, setopen] = useState(false);

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      if (!user) {
        router.push("/login");
        message.success("Logout Successful!");
      }
    });

    return () => {
      unsubscribe();
    };
  }, [auth, router]);

  const onCancel = useCallback(() => {
    setopen(false);
  }, [setopen]);

  return (
    <>
      <Head>
        <title>Hotel CheckIn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <MyHeader />
        <Content style={{ backgroundColor: "#fff" }}>
          <div className="site-layout-content">
            <section className={styles.checkIns}>
              <div>
                <h1 className={styles.title}>CheckIns</h1>
                <p className={styles.description}>
                  Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                </p>
              </div>
              <Button
                type="primary"
                icon={<PlusOutlined />}
                onClick={() => setopen(true)}
                className="add-button"
              >
                Add Check In
              </Button>
            </section>

            <TableWithDetails />

            <Modal
              title="New CheckIn"
              open={open}
              onCancel={onCancel}
              footer={null}
            >
              <MyForm setopen={setopen} />
            </Modal>
          </div>
        </Content>
      </Layout>
    </>
  );
}
